version: '2.1'

services:
  # ==================================
  # C O R E  V A L I D A T O R
  # ==================================
  validator:
    image: hyperledger/sawtooth-validator:1.2.6
    container_name: sawtooth-validator
    expose:
      - 4004
      - 8800
      - 5050
    ports:
      - "4004:4004"
    command: "bash -c \"\
        sawadm keygen --force && \
        sawset genesis -k /etc/sawtooth/keys/validator.priv && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          sawtooth.publisher.max_batches_per_block=500 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
          --scheduler parallel \
        \""

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:chime
    container_name: sawtooth-devmode-engine
    depends_on:
      - validator
    environment:
      - RUST_LOG=debug
    command: devmode-engine-rust -v -C tcp://validator:5050

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.2.6
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - "8008:8008"
    depends_on:
      - validator
    command: sawtooth-rest-api -v -C tcp://validator:4004 --bind rest-api:8008

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.2.6
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    command: settings-tp -v -C tcp://validator:4004

  # ==================================
  # M Y  C U S T O M  T P (ASSET TP)
  # ==================================
  asset-tp:
    build:
      context: .
      dockerfile: docker/Dockerfile.tp-asset
    container_name: sawtooth-asset-tp
    depends_on:
      - validator
    volumes:
      - ./transaction-processors/asset_tp:/project/asset_tp
    command: python3 /project/asset_tp/main.py -C tcp://validator:4004

  # ==================================
  # B A C K E N D  A P I
  # ==================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sawtooth-backend
    ports:
      - "3001:3001"
    environment:
      - REST_API_URL=http://rest-api:8008
      - ZMQ_URL=tcp://validator:4004
    depends_on:
      - rest-api
      - validator

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sawtooth-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
